version: '3.4'

services:
  mkdocs:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5310:5310
    volumes:
      - .:/site
      - venv:/site/.venv
      - ~/.ssh:/home/site/.ssh
    restart: always

volumes:
  venv:
